#ifndef REFLECT_CPP26_UTILS_TO_STRING_UTILS_H
#define REFLECT_CPP26_UTILS_TO_STRING_UTILS_H

#include <reflect_cpp26/utils/config.h>
#include <stddef.h>

// Including minus sign '-'
#define REFLECT_CPP26_MAX_DECIMAL_DIGITS_INT8  4  // -128
#define REFLECT_CPP26_MAX_DECIMAL_DIGITS_INT16 6  // -32768
#define REFLECT_CPP26_MAX_DECIMAL_DIGITS_INT32 11 // -2147483648
#define REFLECT_CPP26_MAX_DECIMAL_DIGITS_INT64 20 // -9223372036854775808

REFLECT_CPP26_EXTERN_C_BEGIN

REFLECT_CPP26_CONSTEXPR size_t reflect_cpp26_max_decimal_digits(size_t bytes)
{
  switch (bytes) {
  case 1:
    return REFLECT_CPP26_MAX_DECIMAL_DIGITS_INT8;
  case 2:
    return REFLECT_CPP26_MAX_DECIMAL_DIGITS_INT16;
  case 4:
    return REFLECT_CPP26_MAX_DECIMAL_DIGITS_INT32;
  case 8:
    return REFLECT_CPP26_MAX_DECIMAL_DIGITS_INT64;
  default:
    REFLECT_CPP26_UNREACHABLE("Invalid size bytes.");
  }
}

REFLECT_CPP26_EXTERN_C_END

#endif // REFLECT_CPP26_UTILS_TO_STRING_UTILS_H
